DROP TABLE IF EXISTS fleet CASCADE;
DROP TABLE IF EXISTS ship CASCADE;
DROP TABLE IF EXISTS assignment CASCADE;
DROP TABLE IF EXISTS sailor CASCADE;
DROP TABLE IF EXISTS rank CASCADE;

CREATE TABLE fleet(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE ship(
  id SERIAL PRIMARY KEY NOT NULL,
  fleetid INTEGER REFERENCES fleet(id) NOT NULL,
  name VARCHAR(255) NOT NULL,
  date_built DATE NOT NULL
);

CREATE TABLE rank(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);

CREATE TABLE sailor(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  dob DATE NOT NULL
);

CREATE TABLE assignment(
  rankid INTEGER REFERENCES rank(id) NOT NULL,
  sailorid INTEGER REFERENCES sailor(id) NOT NULL,
  shipid INTEGER REFERENCES ship(id) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  name VARCHAR(255)
);

